---
title: "Results"
output:
  html_document:
    df_print: paged
---

```{r}
require(factoextra)
require(cluster)
require(tidyverse)
require(terra)
require(raster)
require(sp)
require(randomForest)
require(knitr)
```

```{r}
#plot number of clusters vs. gap statistic
fviz_gap_stat(gap_stat)
```


```{r}
fviz_cluster(km, data = tokmeans)
```

```{r}
pca <- prcomp(tokmeans,  scale = TRUE)
kable(pca$rotation[,1:2], digits = 2, caption = 'Loadings of two main principal components.')
```



```{r}
kable(importance(rf10), digits = 2, col.names = c('Madeira', 'Pará', 'Rondônia', 'Roraima', 'Xingu-Tapajos', 'Decrease Accuracy', 'Decrease Gini') ,caption = 'Variable importace to classfy by province, and for general random forest performance.')
```


```{r}
kable(importance(rf70), digits = 2, col.names = c('Madeira', 'Pará', 'Rondônia', 'Roraima', 'Xingu-Tapajos', 'Decrease Accuracy', 'Decrease Gini') ,caption = 'Variable importace to classfy by province, and for general random forest performance.')
```

## Suplemmentar Material


```{r}
kable(dados10, digits = 2, caption = 'Resume of the sites characteristics considering trees greater than 10 cm')
```

```{r}
kable(dados70, digits = 2, caption = 'Resume of the sites characteristics considering trees greater than 70 cm')
```

